### PR TITLE
LPS-81913 destroy js modules when portlet is distroyed

### PR DESCRIPTION
**Pull request by peterborkuti**
Hi Péter,

Please, review it.
Maybe we should apply it on more places encapsulating it into a tag, but not now.

Thanks
Péter

### CODE REVIEW

**Comment by peterborkuti** [comment]
ci:test

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:reopen

**Comment by brianchiu** [comment]
@peterborkuti I'm going to run another ci test on it. The ci test relevant passed.

**Comment by brianchiu** [comment]
ci:test

**Comment by palius** [comment]
Forwarding it. :)

**Pull request closed without merging**
